"""Add yandex field

Revision ID: 809d684bfa5a
Revises: ce2bdc962243
Create Date: 2026-02-27 14:34:18.054875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809d684bfa5a'
down_revision: Union[str, Sequence[str], None] = 'ce2bdc962243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(op.f('uq_users_yandex_id'), 'users', ['yandex_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_yandex_id'), 'users', type_='unique')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
